set shell=/bin/bash

"Pathogen setup
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
call pathogen#helptags()

"Set leader key
let mapleader = ","

"Set vim to use default os clipboard
set clipboard=unnamed

"Set solarized color scheme
"set background=dark
"colorscheme solarized

"Ensure proper font in MacVim
if has('gui_running')
  set gfn=Monaco:h14
endif

"Sets vim backup directories
set backupdir=$HOME/.vimbackups//,/tmp//
set directory=$HOME/.vimbackups//,/tmp//

"Code formatting
syntax on
set t_Co=256
filetype plugin indent on
set ts=2
set shiftwidth=2
set expandtab
set smarttab
set number

"Column width
set colorcolumn=80
highlight colorcolumn ctermbg=Black

"Maps omnicomplertion to <C-f>
inoremap <C-f> <C-x><C-O>

"Parenthetical completion                                                          
inoremap {<CR> {<CR>}<C-o>O 

"Tab through buffers
" nnoremap <Tab> :bnext<CR>
" nnoremap <S-Tab> :bprevious<CR>

"vim-gitgutter settings
let g:gitgutter_signs = 1
let g:gitgutter_realtime = 1

"vim-go settings
let g:go_disable_autoinstall = 0

"neocomplete settings
let g:neocomplete#enable_at_startup = 1

"Tagbar toggle
nmap <F8> :TagbarToggle<CR>

"Nerdtree toggle
map <F7> :NERDTreeToggle<CR>

"Source files
source $HOME/.vim/source/gotags

"Vdebug
let g:vdebug_options = {'path_maps': {"/vagrant_data": "/Users/gsullice/development/sites"}, 'server': ''}
"let g:vdebug_options['path_maps'] = {"/vagrant_data": "/Users/gsullice/development/sites"}
"let g:vdebug_options['server'] = ""
set path=$PWD/**

let g:gitgutter_realtime = 0

"vim fastunite settings
map <C-p> [unite]p
