"Pathogen setup
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
call pathogen#helptags()

"Set solarized color scheme
set background=dark
colorscheme solarized

"Ensure proper font in MacVim
if has('gui_running')
  set gfn=Monaco:h14
endif

"Sets vim backup directories
set backupdir=$HOME/.vimbackups//,/tmp//
set directory=$HOME/.vimbackups//,/tmp//

"Code formatting
syntax on
set t_Co=16
filetype plugin indent on
set ts=2
set shiftwidth=2
set expandtab
set smarttab
set number

"Maps omnicomplertion to <C-f>
inoremap <C-f> <C-x><C-O>

"vim-gitgutter settings
let g:gitgutter_signs = 1
let g:gitgutter_realtime = 1
