# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export PATH=/usr/local/sbin:$PATH
export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.composer/vendor/bin
export PATH=$PATH:/Applications/MAMP/Library/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/mysql/bin
export PATH=./node_modules/.bin:$PATH

# This configures certain paths specific to your environment, it must be called first.
source $HOME/.dotfiles/config.sh

# These are just the output of `find $HOME/.dotfiles/ -name '*_src.sh'`
source $HOME/.dotfiles/drupal/drush_completion_src.sh
source $HOME/.dotfiles/git/completion_src.sh
source $HOME/.dotfiles/shell/aliases/common_src.sh
source $HOME/.dotfiles/shell/aliases/default_src.sh
source $HOME/.dotfiles/shell/aliases/special_src.sh
source $HOME/.dotfiles/shell/aliases/default_drush.sh
source $HOME/.dotfiles/shell/aliases/utils_src.sh
source $HOME/.dotfiles/shell/completion/completion_src.sh
source $HOME/.dotfiles/shell/config/default_src.sh
source $HOME/.dotfiles/shell/config/ubuntu_src.sh
source $HOME/.dotfiles/shell/path/default_src.sh
source $HOME/.dotfiles/shell/prompt/default_src.sh
source $HOME/.dotfiles/terminal/colors/default_src.sh
source $HOME/.dotfiles/terminal/colors/ubuntu_src.sh
source $HOME/.dotfiles/tmux/default_src.sh
source $HOME/.dotfiles/vim/default_src.sh

export NVM_DIR="/Users/tanner/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
