# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source ~/.dotfiles/source_root.bash
